# Generated by Django 4.2.6 on 2024-05-12 17:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcounties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('provpcode', models.CharField(max_length=254)),
                ('province', models.CharField(max_length=254)),
                ('ctypcode', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('scpcode', models.CharField(max_length=254)),
                ('subcounty', models.CharField(max_length=254)),
                ('dhis2_id', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
