# Generated by Django 4.2.6 on 2024-05-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_subcounties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounties',
            name='dhis2_id',
        ),
        migrations.RemoveField(
            model_name='subcounties',
            name='scpcode',
        ),
    ]
